fix: correct label issue which causes a crash
```python
Traceback (most recent call last):
  File "/Users/matt/Library/Application Support/Blender/3.5/scripts/addons/bpy_externall/__init__.py", line 184, in draw
    col.label('listening on ' + statemachine['tempfile'])
TypeError: UILayout.label(): required parameter "text" to be a keyword argument!
```